- type: job
  id: M14HeadOfRedLine
  name: job-name-head-of-redline
  description: job-description-head-of-redline
  playTimeTracker: M14HeadOfRedLine
  startingGear: M14HeadOfRedLineGear
  icon: "JobIconRedline"
  canBeAntag: false

- type: startingGear
  id: M14HeadOfRedLineGear
  equipment:
    neck: M14ClothingNeckMantleRedLine
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformJumpsuitRedLine
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpack
    pocket1: M14HeadOfRedLineKey
  storage:
    back:
    - M14RadioHandheldRedLine
