- type: job
  id: M14PolitHandRedLine
  name: job-name-political-leader-redline
  description: job-description-political-leader-redline
  playTimeTracker: M14PolitHandRedLine
  startingGear: M14PolitHandRedLineGear
  icon: "JobIconRedline"
  supervisors: job-supervisors-politruk
  canBeAntag: true

- type: startingGear
  id: M14PolitHandRedLineGear
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformJumpsuitRedLine
    id: M14Tablet
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - M14RadioHandheldRedLine
    - M14RedLineKey
