- type: job
  id: M14HeadOfTech
  name: job-name-head-of-tech
  description: job-description-head-of-tech
  playTimeTracker: M14HeadOfTech
  startingGear: M14HeadOfTechGear
  icon: "JobIconTech"
  canBeAntag: false

- type: startingGear
  id: M14HeadOfTechGear
  equipment:
    head: ClothingHeadHatSyndieMAA
    neck: M14ClothingNeckMantleTech
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesHop
    back: ClothingBackpackMerc
    pocket1: M14HeadOfTechKey
    pocket2: M14WeaponShotgunAshot
  storage:
    back:
    - M14RadioHandheldTech
