- type: job
  id: M14TechnicTech
  name: job-name-technic-tech
  description: job-description-technic-tech
  playTimeTracker: M14TechnicTech
  startingGear: M14TechnicTechGear
  supervisors: job-supervisors-tech
  icon: "JobIconTech"
  canBeAntag: true

- type: startingGear
  id: M14TechnicTechGear
  equipment:
    jumpsuit: M14ClothingUniformTelogreykaBrown
    id: M14Tablet
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesColorLightBrown
    back: ClothingBackpack
    belt: ClothingBeltUtilityEngineering
    pocket1: M14WeaponShotgunAshot
  storage:
    back:
    - M14RadioHandheldTech
    - M14KTechKey
