- type: job
  id: M14TradeAgentHansa
  name: job-name-trade-agent-hansa
  description: job-description-trade-agent-hansa
  playTimeTracker: M14TradeAgentHansa
  startingGear: M14TradeAgentHansaGear
  supervisors: job-supervisors-torg
  icon: "JobIconHansa"
  canBeAntag: true

- type: startingGear
  id: M14TradeAgentHansaGear
  equipment:
    head: ClothingHeadHatBowlerHat
    jumpsuit: M14ClothingUniformJumpsuitHansaTradeAgent
    id: M14Tablet
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
    pocket2: M14HansaKey
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampTrader
    - M14HansaPassport
    - M14RadioHandheldHansa
