- type: job
  id: M14Minister
  name: job-name-minister-hydra
  description: job-description-minister-hydra
  playTimeTracker: M14MinisterHydra
  startingGear: M14MinisterHydraGear
  icon: "JobIconHydra"
  supervisors: job-supervisors-predsedatel
  canBeAntag: true

- type: startingGear
  id: M14MinisterHydraGear
  equipment:
    head: ClothingHeadHatBeretSecurityPilot
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformJumpsuitHydra
    id: M14Tablet
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - M14RadioHandheldHydra
    - M14HydraKey
