- type: job
  id: M14SoldierHydra
  name: job-name-soldier-hydra
  description: job-description-soldier-hydra
  playTimeTracker: M14SoldierHydra
  startingGear: M14SoldierHydraGear
  supervisors: job-supervisors-gydra
  icon: "JobIconHydra"
  canBeAntag: true

- type: startingGear
  id: M14SoldierHydraGear
  equipment:
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformJumpsuitHydra
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpack
  storage:
    back:
    - M14RadioHandheldHydra
    - M14HydraKey
